max_compress = 0.2
descent_curve_stride = 20
max_relaxation = 2e4
max_step_size = 1e-3
step_size_searching_samples = 48
epochs = 1  # test; original 20
max_compress_turns = 2000
terminal_phi = 2.0
if_cal_energy = True
S_local_background = 0.338
